# Generated by Django 4.2.1 on 2023-05-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.person'),
        ),
    ]
