# Generated by Django 4.2.1 on 2023-05-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='apartment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
