# Generated by Django 4.2.1 on 2023-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='joku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
