# Generated by Django 4.2.1 on 2023-05-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brande',
        ),
    ]
