# Generated by Django 4.2.1 on 2023-05-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_brande_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
