# Generated by Django 4.2.1 on 2023-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anotherdescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
