# Generated by Django 4.2.1 on 2023-05-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_anotherdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
