# Generated by Django 4.2.1 on 2023-05-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_brand_product_created_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
    ]
