# Generated by Django 4.2.1 on 2023-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaimet', '0002_elain_luokka'),
    ]

    operations = [
        migrations.AddField(
            model_name='elain',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
